openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Get data from endpoint 1
      x-eov-operation-handler: handlers/healthcheck
      operationId: get_ping
      responses:
        '200':
          description: Successful response
    post:
      summary: Create data at endpoint 2
      x-eov-operation-handler: handlers/healthcheck
      operationId: post_ping
      responses:
        '201':
          description: Data created successfully
components: {}

# http://editor.swagger.io/ to see a visual representation of your definitions.