openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0

paths:
  /ping:
    $ref: './ping.yaml'

components: {}

# http://editor.swagger.io/ to see a visual representation of your definitions.